config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :birthdate, :street, :city, :state, :zip, :bio, :newsletter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_form_builder.rb
class MyFormBuilder < ActionView::Helpers::FormBuilder

  def text_field(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def date_select(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def text_area(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def check_box(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def submit(options={})
    @template.content_tag(:div, class: "actions") do
      super
    end
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :newsletter %>
    <%= f.check_box :newsletter %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h3>Form built with a form builder below:</h3>

<%= form_for(person, builder: MyFormBuilder) do |f| %>
  <%= f.text_field :name %>
  <%= f.date_select :birthdate %>
  <%= f.text_field :street %>
  <%= f.text_field :city %>
  <%= f.text_field :state %>
  <%= f.text_field :zip %>
  <%= f.text_area :bio %>
  <%= f.check_box :newsletter %>

  <%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Bio</th>
      <th>Newsletter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.birthdate %></td>
        <td><%= person.street %></td>
        <td><%= person.city %></td>
        <td><%= person.state %></td>
        <td><%= person.zip %></td>
        <td><%= person.bio %></td>
        <td><%= person.newsletter %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @person.birthdate %>
</p>

<p>
  <strong>Street:</strong>
  <%= @person.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @person.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @person.zip %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Newsletter:</strong>
  <%= @person.newsletter %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>